# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PUSHDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PUSHDemo
	pod 'Bugly'
    pod 'JPush'
    pod 'AvoidCrash'
    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'PinYin4Objc'
    pod 'SVProgressHUD'
    pod 'MJExtension'

#    pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

end
